language: node_js
sudo: required
services:
- docker

env:
  global:
    - ORACLE_COOKIE=sqldev
    - ORACLE_DOWNLOAD_DIR=stage
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip

install:
  - .travis/oracle/download.sh
  - unzip -j `find . -name oracle-xe*zip` -d stage *oracle-xe*rpm
  - find . -name oracle-xe*zip -exec rm {} \;
  - curl -o packer.zip https://releases.hashicorp.com/packer/1.1.3/packer_1.1.3_linux_amd64.zip
  - unzip packer.zip

script:
  - ./packer validate oraclexe-ol6.json
  - ./packer validate oraclexe-ol7.json
  - ./packer build oraclexe-ol6.json
  - ./packer build oraclexe-ol7.json

after_script:
  - export DATE=$(date +%y%m%d%H%M)
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker tag oraclexe:ol6 kikitux/oracle:xe-ol6
  - docker tag oraclexe:ol7 kikitux/oracle:xe-ol7
  - docker push kikitux/oracle
