language: node_js
sudo: required
services:
- docker

env:
  global:
    - ORACLE_COOKIE=sqldev
    - ORACLE_FILE=oracle-xe-11.2.0-1.0.x86_64.rpm.zip

before_install:
  - .travis/oracle/download.sh
  - find . -name ${ORACLE_FILE} -ls
  - find . -name ${ORACLE_FILE} -exec md5sum {} \;
  - unzip -l `find . -name ${ORACLE_FILE}`
  - unzip -t `find . -name ${ORACLE_FILE}`
  - unzip `find . -name ${ORACLE_FILE}` -d stage ${ORACLE_FILE%%.zip}
  - curl -o packer.zip https://releases.hashicorp.com/packer/1.1.3/packer_1.1.3_linux_amd64.zip
  - unzip packer.zip

install:
  - ./packer validate oraclexe-ol6.json
  - ./packer validate oraclexe-ol7.json
