language: node_js
sudo: required
services:
- docker

env:
  global:
    - ORACLE_COOKIE=sqldev
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip

before_install:
  - .travis/oracle/download.sh
  - find . -name oracle-xe*zip -ls
  - find . -name oracle-xe*zip -exec md5sum {} \;
  - unzip -l `find . -name oracle-xe*zip`
  - unzip -t `find . -name oracle-xe*zip`
  - unzip `find . -name oracle-xe*zip` -j -d stage oracle-xe*rpm
  - curl -o packer.zip https://releases.hashicorp.com/packer/1.1.3/packer_1.1.3_linux_amd64.zip
  - unzip packer.zip

install:
  - ./packer validate oraclexe-ol6.json
  - ./packer validate oraclexe-ol7.json
